### ISSUE TITLE
feat: Perhaps an Github Action is needed to publish the extension

### ISSUE THREAD

**Issue by huang12zheng** [Nash0x7E2/awesome-flutter-snippets#67]
this issue ref to https://github.com/Nash0x7E2/awesome-flutter-snippets/issues/31
I might be able to help make that happen

**Comment by huang12zheng** [comment]
```yaml
on:
  push:
  workflow_dispatch:

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
```
